### ISSUE TITLE
Invalid website message when running a local test job

### ISSUE THREAD

**Issue by dumitrescustefan** [adobe/frontend-regression-validator#3]
Hi, 

When entering a local website, i get the job failed with *Status: Invalid website*.

I opened two dummy websites with ``php -S 127.0.0.1:8100`` (and port 8101), with two index.html files containing:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title></title>
</head>
<body>
<img src="new_shift.png"/>
</body>
</html>
``` 

each with a different png file. They render okay in the browser, but in fred's job interface I get: 

```
Baseline URL: http://127.0.0.1:8100/index.html
Updated URL: http://127.0.0.1:8101/index.html
Max depth for crawler: 1
Max URLs for crawler: 1
Prefix: out1
Status: Invalid website
```

Error from the local FRED instance (started with ``run.py``):
```
127.0.0.1 - - [13/Jan/2020 10:33:36] "POST /api/verify HTTP/1.1" 200 -
Traceback (most recent call last):
  File "worker_crawl.py", line 117, in <module>
    args.auth_baseline_password, args.auth_updated_username, args.auth_updated_password)
  File "worker_crawl.py", line 32, in work
    crawled_baseline = get_recursive_urls(baseline_url, max_depth, max_urls)[:max_urls]
  File "/Users/sdumitre/work/frontend-regression-validator/fred/crawler/crawler.py", line 51, in get_recursive_urls
    asyncio.get_event_loop().run_until_complete(get_page(page, parent_url))
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/Users/sdumitre/work/frontend-regression-validator/fred/crawler/crawler.py", line 19, in get_page
    await page.goto(url)
  File "/Users/sdumitre/virtual/p3/lib/python3.7/site-packages/pyppeteer/page.py", line 856, in goto
    raise PageError(result)
pyppeteer.errors.PageError: net::ERR_CONNECTION_REFUSED at http://:@127.0.0.1
```

Tx

**Comment by dumitrescustefan** [comment]
no longer relevant, we're updating soon to a v2, closing.
