### ISSUE TITLE
Error status message

### ISSUE THREAD

**Issue by dumitrescustefan** [adobe/frontend-regression-validator#4]
Running several tests (locally) I've come up with several different errors in the console, but the message on the UI seems to always be the same : "Invalid website". 

I think it should reflect the actual error thrown. For example:
```
Traceback (most recent call last):
  File "worker_predict.py", line 78, in <module>
    work(args.baseline_dir, args.updated_dir, args.prefix)
  File "worker_predict.py", line 54, in work
    updated_network_log_file)
  File "/Users/sdumitre/work/frontend-regression-validator/fred/process/process.py", line 8, in __init__
    self.baseline_js_logs = JavascriptLogPreprocessor(baseline_js_log_file)
  File "/Users/sdumitre/work/frontend-regression-validator/fred/data/log_preprocess.py", line 7, in __init__
    self.logs = json.load(open(log_file, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: './tmp/1_baseline/buttons_1_js_log.json'
```
gives the ``Status: Invalid website`` message. Guess this is a low priority issue, but it for non-coder users this error message is confusing.

**Comment by dumitrescustefan** [comment]
no longer relevant, we're updating soon to a v2, closing.
